[workspace]

members = [
    "grammar/variables",
    "grammar/basic-types",
    "grammar/struct-enum",
    "grammar/control-flow",
    "grammar/string",
    "grammar/tuple",
    "grammar/pattern-matching",
    "grammar/method",

    "exercise/scrape_url",
    "exercise/httpie"
]
