[workspace]

members = [
    "grammar/variables",
    "grammar/basic-types",
    "grammar/struct-enum",
    "grammar/control-flow",
    "grammar/string",
    "grammar/tuple",
    
    "exercise/scrape_url",
    "exercise/httpie"
]
